#!/bin/sh -e

export version=1.0.8
export sources="https://sourceware.org/pub/bzip2/bzip2-$version.tar.gz
patches/makefile-CFLAGS.patch"

build() {
    for p in patches/*; do
        patch -p1 < "$p"
    done

    make CC="$CC $CFLAGS -fPIC $LDFLAGS" -f Makefile-libbz2_so
    make CC="$CC $CFLAGS -static -fPIC $LDFLAGS" bzip2

    mkdir -p "$1/usr/lib"
    mkdir -p "$1/usr/bin"
    mkdir -p "$1/usr/include"
    mkdir -p "$1/usr/share/man/man1"

    cp -f \
       bzip2 \
       bzdiff \
       bzgrep \
       bzmore \
       "$1/usr/bin"

    cp -f \
       libbz2.so.1.0.8 \
       libbz2.a \
       "$1/usr/lib"

    cp -f bzip2.1 "$1/usr/share/man/man1"
    cp -f bzlib.h "$1/usr/include"

    ln -sf libbz2.so.1.0.8 "$1/usr/lib/libbz2.so"
    ln -sf libbz2.so.1.0.8 "$1/usr/lib/libbz2.so.1"
    ln -sf libbz2.so.1.0.8 "$1/usr/lib/libbz2.so.1.0"
    ln -sf bzip2 "$1/usr/bin/bunzip2"
    ln -sf bzip2 "$1/usr/bin/bzcat"
}
