#!/bin/sh -e

export version=2.04
export sources="https://ftp.gnu.org/gnu/grub/grub-$version.tar.xz"

_build_grub_flavor() {
    _pkg_dir="$1"
    _flavor="$2"
    shift 2

    mkdir "build_$_flavor"
    cd "build_$_flavor"
    ./configure \
        --prefix=/usr \
        --sysconfdir=/etc \
        --mandir=/usr/share/man \
        --localstatedir=/var \
        --disable-nls \
        --disable-werror \
        --disable-grub-mkfont \
        --disable-grub-mount \
        "$@"
    make
    make DESTDIR="$_pkg_dir" install-strip
}

build() {
    # Remove dependency on python
    export PYTHON=/bin/true
    sed -i 's/mv $@.new $@/:/g' ./*/Makefile.in

    _build_grub_flavor "$1" pc --with-platform=pc
    _build_grub_flavor "$1" efi --with-platform=efi --disable-efiemu
}
