#!/bin/sh -e

export version=5.11
export sources="https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-$version.tar.xz"

build() {
    make headers
    make headers_install ARCH=x86_64 INSTALL_HDR_PATH="$1/usr"
}
