#!/bin/sh -e

export version=5.12
export sources="https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-$version.tar.xz"

build() {
    make HOSTCC="$CC" headers

    # Avoid the dependency on rsync.
    find usr/include -name \*.h -type f | while read -r file; do
	install -Dm644 "$file" "$1/$file"
    done
}
