#!/bin/sh -e

# Looking at the number of audits OpenSSL received it might not be really useful
# to switch to LibreSSL, knowing all the problems it can cause. However, WolfSSL
# and BearSSL are really interesting because they have a really small
# codebase. BearSSL might be considered when it will have TLS 1.3 support. This
# protocol is already supported by WolfSSL, plus it has a compatibility layer
# with OpenSSL which is practical and will avoid having to use a lot of
# patches. But, for now, we'll stick to OpenSSL.

export version=1.1.1j
export sources="https://www.openssl.org/source/openssl-$version.tar.gz
patches/man-section.patch"
export depends="perl"

build() {
    for p in patches/*; do
        patch -p1 < "$p"
    done
    perl ./Configure linux-x86_64 \
         --prefix=/usr \
         --libdir=lib \
         --openssldir=/etc/ssl \
         shared no-zlib enable-ec_nistp_64_gcc_128 \
         no-async no-comp no-idea no-mdc2 no-rc5 no-ec2m \
         no-sm2 no-sm4 no-ssl2 no-ssl3 no-seed \
         no-weak-ssl-ciphers \
         "$CPPFLAGS" "$CFLAGS" "$LDFLAGS" -Wa,--noexecstack
    make

    make DESTDIR="$1" install
    rm "$1/usr/bin/c_rehash"
}
