#!/bin/sh -e

export version=10.2.0
export sources="https://gcc.gnu.org/pub/gcc/releases/gcc-$version/gcc-$version.tar.xz
https://ftp.gnu.org/gnu/gmp/gmp-6.1.2.tar.xz gmp
https://ftp.gnu.org/gnu/mpfr/mpfr-4.0.2.tar.xz mpfr
https://ftp.gnu.org/gnu/mpc/mpc-1.1.0.tar.gz mpc
https://gcc.gnu.org/pub/gcc/infrastructure/isl-0.18.tar.bz2 isl"

build() {
    mkdir build && cd build
    ../configure \
        --prefix=/usr \
        --disable-multilib \
        --disable-symvers \
        --disable-libmpx \
        --disable-libmudflap \
        --disable-werror \
        --disable-fixed-point \
        --disable-libstdcxx-pch \
        --disable-nls \
        --enable-checking=release \
        --enable-__cxa_atexit \
        --enable-default-pie \
        --enable-default-ssp \
        --enable-shared \
        --enable-threads \
        --enable-tls \
        --enable-languages=c,c++ \
        --without-included-gettext \
        --build=x86_64-linux-musl \
        --host=x86_64-linux-musl \
        --target=x86_64-linux-musl \
        --disable-bootstrap
    make
    make DESTDIR="$1" install
}
