#!/bin/sh -e

export version="3.7.5"
export sources="https://ftp.gnu.org/gnu/bison/bison-$version.tar.xz"
export depends="m4"

build() {
    ./configure \
        --prefix=/usr \
        --disable-nls \
        --mandir=/usr/share/man
    make
    make DESTDIR="$1" install
}
