#!/bin/sh -e

export version=1.32.1
export sources="https://busybox.net/downloads/busybox-$version.tar.bz2"

build() {
    make defconfig
    sed -i \
        -e 's/# CONFIG_STATIC is not set/CONFIG_STATIC=y/' \
        -e "s/CONFIG_EXTRA_COMPAT=y/CONFIG_EXTRA_COMPAT=n/" \
        -e "s/CONFIG_EXTRA_CFLAGS=\"\"/CONFIG_EXTRA_CFLAGS=\"$CFLAGS\"/" \
        .config
    make
    cp busybox "$1/usr/bin/busybox"
    for bin in $(./busybox --list); do
        ln -s busybox "$1/usr/bin/$bin"
    done
}
