#!/bin/sh -e

export version=5.32.1
export sources="https://www.cpan.org/src/5.0/perl-$version.tar.xz"
export depends="zlib bzip2"

build() {
    export BUILD_ZLIB=0
    export BUILD_BZIP2=0
    export LDFLAGS="$LDFLAGS -pthread"
    export CFLAGS="$CFLAGS -DNO_POSIX_2008_LOCALE -D_GNU_SOURCE"
    export BZIP2_LIB=/usr/lib
    export BZIP2_INCLUDE=/usr/include

    ./Configure \
        -des \
        -Dcccdlflags=-fPIC \
        -Dccdlflags='-rdynamic' \
        -Dccflags="$CFLAGS" \
        -Dprefix=/usr \
        -Dvendorprefix=/usr \
        -Dsiteprefix=/usr/local \
        -Dlocincpth=' ' \
        -Duselargefiles \
        -Dusethreads \
        -Duseshrplib \
        -Dd_semctl_semun \
        -Dman1ext='1' \
        -Ud_csh \
        -Dcc="$CC" \
        -Dusenm

    make
    make DESTDIR="$1" install
}
