#!/bin/sh -e

export version=1.2.11
export source="https://zlib.net/zlib-$version.tar.gz"

build() {
    ./configure \
        --prefix=/usr \
        --libdir=/usr/lib \
        --shared
    make
    make DESTDIR="$1" install
}
